---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/todos":
    get:
      summary: Lists todos
      tags:
      - Todo
      description: Lists todo
      parameters:
      - name: done
        in: query
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    task:
                      type: string
                    done:
                      type: boolean
                    due_by:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    url:
                      type: string
                  example:
                    id: 1
                    task: Water plants
                    done: false
                    due_by: '2022-06-01'
                    created_at: '2022-06-01'
                    updated_at: '2022-06-01'
                    url: https://open-api-swagger.herokuapp.com/api/v1/todos/1.json
    post:
      summary: Creates a todo
      tags:
      - Todo
      description: Creates a new todo from provided data
      operationId: createTodo
      security:
      - JWT: []
      parameters: []
      responses:
        '201':
          description: success
          content:
            application/json:
              example:
                api_v1_todo:
                  task: Water plants
                  done: false
                  due_by: '2022-06-01'
        '422':
          description: invalid request
          content:
            application/json:
              example:
                done: false
                due_by: '2022-06-01'
        '401':
          description: unauthorized request
          content:
            application/json:
              example:
                api_v1_todo:
                  task: Water plants
                  done: false
                  due_by: '2022-06-01'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
                done:
                  type: boolean
                  nullable: true
                due_by:
                  type: string
                  nullable: true
              example:
                api_v1_todo:
                  task: Water plants
                  done: false
                  due_by: '2022-06-01'
              required:
              - task
              - done
              - due_by
  "/api/v1/todos/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Retrieves a todo
      tags:
      - Todo
      description: Retrieves a specific todo by id
      operationId: getTodo
      responses:
        '404':
          description: not found
        '200':
          description: success
          content:
            application/json:
              example:
                api_v1_todo:
                  id: 1
                  task: Water plants
                  done: false
                  due_by: '2022-06-01'
                  created_at: '2022-06-01'
                  updated_at: '2022-06-01'
                  url: https://open-api-swagger.herokuapp.com/api/v1/todos/1.json
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  task:
                    type: string
                  done:
                    type: boolean
                  due_by:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  url:
                    type: string
    put:
      summary: Updates a todo
      tags:
      - Todo
      description: Updates a specific todo by id
      operationId: updateTodo
      security:
      - JWT: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                api_v1_todo:
                  task: Water plants
                  done: false
                  due_by: '2022-06-01'
        '422':
          description: invalid request
        '401':
          description: unauthorized request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
                done:
                  type: boolean
                due_by:
                  type: string
              example:
                api_v1_todo:
                  task: Water plants
                  done: false
                  due_by: '2022-06-01'
    patch:
      summary: Updates a todo
      tags:
      - Todo
      description: Updates a specific todo by id
      operationId: patchTodo
      security:
      - JWT: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                done: false
        '422':
          description: invalid request
        '401':
          description: unauthorized request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
                done:
                  type: boolean
                due_by:
                  type: string
              example:
                api_v1_todo:
                  done: true
    delete:
      summary: Deletes a todo
      tags:
      - Todo
      description: Deletes a specific todo by id
      operationId: deleteTodo
      security:
      - JWT: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: success
servers:
- url: https://open-api-swagger.herokuapp.com
  variables:
    defaultHost:
      default: open-api-swagger.herokuapp.com
components:
  securitySchemes:
    JWT:
      type: apiKey
      name: Authorization
      in: header
